#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output DP-0 --primary --mode 1920x1080 --rate 120 --rotate normal --output HDMI-0 --mode 1920x1080 --rotate normal --right-of DP-0

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor DP-0 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
