#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output DP-0 --primary --mode 1920x1080 --rate 120 --rotate normal --output HDMI-0 --mode 1920x1080 --rotate normal --right-of DP-0

feh --bg-fill $HOME/Pictures/rakka.jpg &
wal -i $HOME/Pictures/rakka.jpg &
. "${HOME}/.cache/wal/colors.sh"


bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc config focus_follows_pointer true

bspc config border_width         2
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor DP-0 -d Terminal Firefox
bspc monitor HDMI-0 -d Discord Spotify

bspc rule -a kitty desktop='Terminal' follow=on focus=on
bspc rule -a firefox desktop='Firefox' follow=on focus=on

bspc rule -a discord desktop='Discord' focus=on
bspc rule -a spotify desktop='Spotify' follow=on focus=on
