# Shell variables
# Generated by 'wal'
wallpaper='/home/lucy/Pictures/rakka.jpg'

# Special
background='#1e0e16'
foreground='#ebe0c7'
cursor='#ebe0c7'

# Colors
color0='#1e0e16'
color1='#9B6854'
color2='#B28E66'
color3='#D3A167'
color4='#E8C474'
color5='#A87A82'
color6='#D4B28B'
color7='#ebe0c7'
color8='#a49c8b'
color9='#9B6854'
color10='#B28E66'
color11='#D3A167'
color12='#E8C474'
color13='#A87A82'
color14='#D4B28B'
color15='#ebe0c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
