--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/lucy/Pictures/rakka.jpg"

-- Special
background="#1e0e16"
foreground="#ebe0c7"
cursor="#ebe0c7"

-- Colors
color0="#1e0e16"
color1="#9B6854"
color2="#B28E66"
color3="#D3A167"
color4="#E8C474"
color5="#A87A82"
color6="#D4B28B"
color7="#ebe0c7"
color8="#a49c8b"
color9="#9B6854"
color10="#B28E66"
color11="#D3A167"
color12="#E8C474"
color13="#A87A82"
color14="#D4B28B"
color15="#ebe0c7"
